apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env
  namespace: airflow
data:
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE: apache/airflow:2.7.2
  AIRFLOW__KUBERNETES__NAMESPACE: airflow
  AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8888"