apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      serviceAccountName: airflow-sa
      initContainers:
        - name: airflow-db-init
          image: apache/airflow:2.7.2
          command:
            - /bin/bash
            - -c
            - |
              if airflow db check; then
                echo "Database already initialized, skipping db init."
              else
                echo "Initializing Airflow database..."
                airflow db init
              fi
          envFrom:
            - configMapRef:
                name: airflow-env
            - secretRef:
                name: airflow-postgres-secret
      containers:
        - name: airflow-webserver
          image: jaymztheking/airflow:custom
          args: ["webserver"]
          envFrom:
            - configMapRef:
                name: airflow-env
            - secretRef:
                name: airflow-postgres-secret
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: airflow-dags
              mountPath: /opt/airflow/dags
            - name: airflow-logs
              mountPath: /opt/airflow/logs
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg              
        - name: airflow-scheduler
          image: jaymztheking/airflow:custom
          args: ["scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-env
            - secretRef:
                name: airflow-postgres-secret
          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs
            - name: airflow-dags
              mountPath: /opt/airflow/dags
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg            
        - name: airflow-triggerer
          image: jaymztheking/airflow:custom
          args: ["triggerer"]
          envFrom:
            - configMapRef:
                name: airflow-env
            - secretRef:
                name: airflow-postgres-secret
          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs
            - name: airflow-dags
              mountPath: /opt/airflow/dags
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
      volumes:
        - name: airflow-dags
          emptyDir: {}
        - name: airflow-logs
          emptyDir: {}
        - name: airflow-config
          configMap:
            name: airflow-config
