apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: airflow
  name: airflow-rolebinding
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io
