name: Deploy DAGs to Airflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up kubectl and configure kubeconfig
      - name: Set up kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      # Load kubeconfig from secret
      - name: Load kubeconfig from secret
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig
          echo "KUBECONFIG is set to $(pwd)/kubeconfig"

      # Debug kubeconfig file
      - name: Debug kubeconfig
        run: |
          echo "Verifying kubeconfig contents..."
          ls -l kubeconfig
          head -n 10 kubeconfig
          grep "clusters" kubeconfig || echo "No clusters found in kubeconfig"
          grep "contexts" kubeconfig || echo "No contexts found in kubeconfig"

      # Verify kubectl connectivity
      - name: Verify kubectl
        run: |
          sudo kubectl get nodes --kubeconfig=$(pwd)/kubeconfig
