name: Deploy DAGs to Airflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up kubectl and configure kubeconfig
      - name: Set up kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Load kubeconfig from secret
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          echo "Kubeconfig file successfully created."

      # Check contents of kubeconfig
      - name: Debug kubeconfig
        run: |
          echo "Checking kubeconfig file contents..."
          ls -l $PWD/kubeconfig
          cat kubeconfig | head -n 10
          grep "clusters" kubeconfig || echo "No clusters found in kubeconfig"
          grep "contexts" kubeconfig || echo "No contexts found in kubeconfig"

      # Verify kubectl connectivity
      - name: Verify kubectl
        run: |
          sudo kubectl get nodes
