name: Deploy DAGs to Airflow

on:
  push:
    paths:
      - "dags/**"

jobs:
  deploy-dags:
    runs-on: self-hosted 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy DAGs to Airflow containers
        run: |
          # Get the list of Airflow pods
          PODS=$(sudo kubectl get pods -n airflow -l app=airflow -o jsonpath='{.items[*].metadata.name}')

          # Copy the dags folder to each container in every Airflow pod
          for pod in $PODS; do
            for container in airflow-webserver airflow-scheduler airflow-triggerer; do
              echo "Copying DAGs to $container in pod $pod..."
              sudo kubectl cp ./dags/. "$pod":/opt/airflow/dags -n airflow -c "$container"
            done
          done
