name: Deploy DAGs to Airflow

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up kubectl and configure kubeconfig
      - name: Set up kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Load kubeconfig from secret
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          echo "Kubeconfig successfully loaded."

      # Verify kubectl connectivity
      - name: Verify kubectl
        run: |
          sudo kubectl get nodes

      # Deploy DAGs to Airflow Pods
      - name: Deploy DAGs
        env:
          PODS: $(sudo kubectl get pods -n airflow -l app=airflow -o jsonpath='{.items[*].metadata.name}')
        run: |
          echo "Copying DAGs to Airflow pods..."
          for pod in $PODS; do
            echo "Copying DAGs to $pod"
            sudo kubectl cp dags/ $pod:/opt/airflow/dags -n airflow
          done
